language: go

go:
  - 1.8.3

services:
  - docker
  - redis-server

before_install:
  - pip install --user awscli
  - aws s3 ls
  - aws s3 ls s3://synchronizer-temp

before_script:
  - BUILD_VERSION=$(tail -n 1 splitio/version.go | awk '{print $4}' | tr -d '"')
  - echo ${BUILD_VERSION}
  - mkdir -p release/deploy/synchronizer/${BUILD_VERSION}

script:
  #- go test -v -cover $(go list ./... | grep -v /vendor/)
  - echo "hola"

after_success:
  #- docker build -t splitsoftware/split-synchronizer:${BUILD_VERSION} -t splitsoftware/split-synchronizer:latest .
  - cd release
  - sh build.sh

before_deploy:
  # Move files
  - cat versions.pre.html versions.html versions.pos.html > deploy/synchronizer/versions.html
  - cp install_linux_*.bin deploy/synchronizer/${BUILD_VERSION}
  - cp install_osx_*.bin deploy/synchronizer/${BUILD_VERSION}
  - cp split-sync-win_*.zip deploy/synchronizer/${BUILD_VERSION}
  # Create copies
  - cd deploy/synchronizer/${BUILD_VERSION}
  - cp install_linux_*.bin ../install_linux.bin
  - cp install_osx_*.bin ../install_osx.bin
  - cp split-sync-win_*.zip ../split-sync-win.zip
  # List files
  - ls -R ${TRAVIS_BUILD_DIR}/release/deploy
  #- aws s3 sync ${TRAVIS_BUILD_DIR}/release/deploy/synchronizer s3://synchronizer-temp/

deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: "synchronizer-temp"
    region: us-east-1
    #local_dir: ${TRAVIS_BUILD_DIR}/release/deploy/synchronizer
    skip_cleanup: true
    #acl: public_read
    on:
      branch: travis-build-INFRA-1014
  - provider: script
    script: bash docker_push
    on:
      branch: master
