[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/splitio/go-split-commons"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "=1.2"

[[constraint]]
  name = "github.com/gin-contrib/gzip"
  branch = "master"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "=1.3.1"
