name: unstable
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'

jobs:
  push-synchronizer-docker-image:
    name: Build and Push Sync Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: splitio-docker-dev.jfrog.io
          username: ${{ secrets.ARTIFACTORY_DOCKER_USER }}
          password: ${{ secrets.ARTIFACTORY_DOCKER_PASS }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get short hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Generate entrypoints
        run: make entrypoints
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.synchronizer
          push: true
          tags: splitio-docker-dev.jfrog.io/split-synchronizer:${{ env.SHORT_SHA }}

  push-split-proxy-image:
    name: Build and Push Proxy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: splitio-docker-dev.jfrog.io
          username: ${{ secrets.ARTIFACTORY_DOCKER_USER }}
          password: ${{ secrets.ARTIFACTORY_DOCKER_PASS }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get short hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Generate entrypoints
        run: make entrypoints
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.proxy
          push: true
          tags: splitio-docker-dev.jfrog.io/split-proxy:${{ env.SHORT_SHA }}
